# Generated by Django 2.2.2 on 2019-06-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=300)),
                ('img', models.ImageField(upload_to='')),
                ('filters', models.TextField(blank=True, help_text='Filters by which you can search, write a comma', max_length=800)),
                ('properties', models.TextField(blank=True, help_text='Possible properties of items in this category, write a comma', max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('stars', models.IntegerField()),
                ('body', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.CharField(max_length=3000)),
                ('props', models.CharField(help_text='Possible properties of item like this - "Color: red", write a comma', max_length=1000)),
                ('img', models.ImageField(upload_to='')),
                ('stars', models.FloatField()),
                ('prise', models.FloatField()),
                ('category', models.ManyToManyField(related_name='item', to='restapi.Category')),
            ],
        ),
    ]
