# Generated by Django 2.2.2 on 2019-06-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='types',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
