# Generated by Django 2.2.2 on 2019-06-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_review_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='reviews',
            field=models.ManyToManyField(related_name='item', to='restapi.Review'),
        ),
    ]
