# Generated by Django 2.2.2 on 2019-06-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20190626_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ManyToManyField(related_name='review', to='restapi.Item'),
        ),
    ]
