# Generated by Django 2.2.2 on 2019-06-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20190626_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='item',
        ),
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='restapi.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.FloatField(),
        ),
    ]
